Updated config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,38 +1,28 @@
 version: 2.1
 
 jobs:
-  test-build:
-    docker:
+    check-docker-code:
+      docker:
       - image: python:3.7.3-stretch
-
-    steps:
+      working_directory: ~/repo
+      steps:
       - checkout
-
-      - restore_cache:
-          keys:
-            - v1-dependencies-{{ checksum "requirements.txt" }}
-            # fallback to using the latest cache if no exact match is found
-            - v1-dependencies-
-
-      # run build
       - run:
-          name: install dependencies
+          name: Installing Linters
           command: |
-            python3 -m venv venv
-            . venv/bin/activate
             make install
-      # run lint
       - run:
-          name: run lint
-          command: |
-            . venv/bin/activate
+          name: run lint on Dockerfile
+          command: |         
             make lint
-      - save_cache:
-          paths:
-            - ./venv
-          key: v1-dependencies-{{ checksum "requirements.txt" }}
+            RESULT=$?
+            if [ ${RESULT} -eq 0 ]; then
+              echo "successfully linted files - proceeding to build image"
+            else
+              echo "failed to lint files - please fix and try again"
+            fi
 
 workflows:
   default:
     jobs:
-      - test-build
+      - check-docker-code
